// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import TermsController from "controllers/terms_controller"
application.register("terms", TermsController)

import PostPointsController from "controllers/post_points_controller"
application.register("post-points", PostPointsController)
